app = "qrhub"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8001"

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 80
    hard_limit = 100

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
  cpus = 1

[[mounts]]
  source = "app_uploads"
  destination = "/app/uploads"
  initial_size = "1gb"

[deploy]
  release_command = "echo 'Release OK'"
